### PR TITLE
revert to working version

### PR DESCRIPTION
**Pull request by proyvind**
revert sabotage as well..

### CODE REVIEW

**Comment by tpgxyz** [comment]
@proyvind  We have drop uclibc support in 2014 year. Please remove this uclibc crap.

**Comment by fedya** [comment]
Proyvind we were dropped it years ago, and no reason to keep it or restore again.

**Comment by proyvind** [comment]
I need it, and 
As I am getting back to distro development again,

**Comment by proyvind** [comment]
I need it for several purposes.
As I am getting back to distro development, where especially parts of it relies on it, it gets problematic if I have to fork all these packages and maintain separately, and be a loss to you if I weren't able to make pull requests with fixes to interest for you.

There's already also a package of actual usage to most already available in cooker (ucDrakx), which relies on the uClibc packages as buildrequires. This package provides functionality satisfying two past features proposed & accepted in ancient technical specs:
http://archive.openmandriva.org/wiki/en/index.php?title=2012.0_specs_proposal#Implement_a_easy-to-use_recovery_tool
http://archive.openmandriva.org/wiki/en/index.php?title=2012.0_specs_proposal#Add_recovery_environment_to_initramfs

The only package that really has been bothered by uClibc is systemd, for which I only need udev, so since uClibc build of systemd seems to have motivated you from disabling it all throughout the distro as well following, there's no good reason for disabling this for any packages as they're not interfering, and I'd be more than happy to attend to fix any issues caused by together with additional extra attention to the packages otherwise.

**Comment by tpgxyz** [comment]
OpenMandriva is a free of uclibc broken by design support and it will stay as it is now. All the uclibc crap has been removed.

**Comment by proyvind** [comment]
broken by design?

In what way?

**Comment by proyvind** [comment]
I'm still waiting for my question to be asked and reasonable motivations for removing extensive work I've put into the distro and which things developed built upon such as ucDrakx relies on it.

As the builds doesn't affect the other packages built for those providing uClibc builds and can peacefully co-exist in distribution without even need for disabling, you have no reasonable excuse for neither disabling nor removing it.

It does actually provide quite valuable functionality with an embedded toolchain and environment maintained within distro, something no other mainstream distro offers, whereas only niché embedded distros such as yocto etc. is providing this currently with a lot more hazzle to work with.

I am also not the only person who wants to have uclibc builds in place with the interest in toolchains intended for embedded development, bero also sees the benefits, possible use cases for and importance of providing.

What will be the next toolchain work of mine you'll remove? Cross toolchain support?

Your argument about uClibc being broken by design is something you're not able to back up, so let's behave like and keep focus objective & technical...

**Comment by tpgxyz** [comment]
Feel free to use musl.  uclibc is gone and there is no point in having it around, yet there are no benefits for OpenMandriva Lx distro.

**Comment by proyvind** [comment]
uClibc will be replaced by uClibc-ng fork, which will pretty much work as a drop-in replacement with also a stable ABI.

I've spent many years and efforts on doing work on uClibc toolchain, with intimate knowledge of and interest in doing further development on, just as I've been doing for uClibc++.

From my past experimenting, building against uClibc also producing smaller binaries, given it preference.

I've already pointed out the benefits, for me/us we also have professional interest with potential greater benefits to the project than most other stuff..

**Pull request closed without merging**
